package sv.global.colas.entities;

// Generated 10-30-2009 11:58:06 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeNotifEmail generated by hbm2java
 */
@Entity
@Table(name = "DE_NOTIF_EMAIL", schema = "DECLARACIONES")
public class DeNotifEmail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6232800395436905835L;
	private Long iindice;
	private String cemail;
	private String nit;
	private String semailPara;
	private boolean bestado;
	private Date fhregistro;
	private Date fhnotificado;
	private String sparam1;
	private String sparam2;
	private String sparam3;

	public DeNotifEmail() {
	}

	public DeNotifEmail(Long IIndice, String CEmail, String nit,
			boolean BEstado, Date fhRegistro) {
		this.iindice = IIndice;
		this.cemail = CEmail;
		this.nit = nit;
		this.bestado = BEstado;
		this.fhregistro = fhRegistro;
	}

	public DeNotifEmail(Long IIndice, String CEmail, String nit,
			String SEmailPara, boolean BEstado, Date fhRegistro,
			Date fhNotificado, String SParam1, String SParam2, String SParam3) {
		this.iindice = IIndice;
		this.cemail = CEmail;
		this.nit = nit;
		this.semailPara = SEmailPara;
		this.bestado = BEstado;
		this.fhregistro = fhRegistro;
		this.fhnotificado = fhNotificado;
		this.sparam1 = SParam1;
		this.sparam2 = SParam2;
		this.sparam3 = SParam3;
	}

	@Id
	@Column(name = "I_INDICE", nullable = false, precision = 10, scale = 0)
	public Long getIindice() {
		return this.iindice;
	}

	public void setIindice(Long IIndice) {
		this.iindice = IIndice;
	}

	@Column(name = "C_EMAIL", nullable = false, length = 2)
	public String getCemail() {
		return this.cemail;
	}

	public void setCemail(String CEmail) {
		this.cemail = CEmail;
	}

	@Column(name = "NIT", nullable = false, length = 14)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "S_EMAIL_PARA", length = 100)
	public String getSemailPara() {
		return this.semailPara;
	}

	public void setSemailPara(String SEmailPara) {
		this.semailPara = SEmailPara;
	}

	@Column(name = "B_ESTADO", nullable = false, precision = 1, scale = 0)
	public boolean isBestado() {
		return this.bestado;
	}

	public void setBestado(boolean BEstado) {
		this.bestado = BEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_REGISTRO", nullable = false, length = 7)
	public Date getFhregistro() {
		return this.fhregistro;
	}

	public void setFhregistro(Date fhRegistro) {
		this.fhregistro = fhRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FH_NOTIFICADO", length = 7)
	public Date getFhnotificado() {
		return this.fhnotificado;
	}

	public void setFhnotificado(Date fhNotificado) {
		this.fhnotificado = fhNotificado;
	}

	@Column(name = "S_PARAM1", length = 50)
	public String getSparam1() {
		return this.sparam1;
	}

	public void setSparam1(String SParam1) {
		this.sparam1 = SParam1;
	}

	@Column(name = "S_PARAM2", length = 50)
	public String getSparam2() {
		return this.sparam2;
	}

	public void setSparam2(String SParam2) {
		this.sparam2 = SParam2;
	}

	@Column(name = "S_PARAM3", length = 50)
	public String getSparam3() {
		return this.sparam3;
	}

	public void setSparam3(String SParam3) {
		this.sparam3 = SParam3;
	}

}
