package sv.global.colas.entities;

// Generated Dec 12, 2007 1:25:05 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EdDetalleNotaId generated by hbm2java
 */
@Embeddable
public class EdDetalleNotaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6188655209015558426L;
	private String nnotaAbono;
	private Integer cformulario;
	private Integer cversion;

	public EdDetalleNotaId() {
	}

	public EdDetalleNotaId(String nnotaAbono, Integer cformulario, Integer cversion) {
		this.nnotaAbono = nnotaAbono;
		this.cformulario = cformulario;
		this.cversion = cversion;
	}

	@Column(name = "N_NOTA_ABONO", nullable = false, length = 12)
	public String getNnotaAbono() {
		return this.nnotaAbono;
	}

	public void setNnotaAbono(String nnotaAbono) {
		this.nnotaAbono = nnotaAbono;
	}

	@Column(name = "C_FORMULARIO", nullable = false, precision = 4, scale = 0)
	public Integer getCformulario() {
		return this.cformulario;
	}

	public void setCformulario(int cformulario) {
		this.cformulario = cformulario;
	}

	@Column(name = "C_VERSION", nullable = false, precision = 4, scale = 0)
	public Integer getCversion() {
		return this.cversion;
	}

	public void setCversion(int cversion) {
		this.cversion = cversion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EdDetalleNotaId))
			return false;
		EdDetalleNotaId castOther = (EdDetalleNotaId) other;

		return ((this.getNnotaAbono() == castOther.getNnotaAbono()) || (this
				.getNnotaAbono() != null
				&& castOther.getNnotaAbono() != null && this.getNnotaAbono()
				.equals(castOther.getNnotaAbono())))
				&& (this.getCformulario() == castOther.getCformulario())
				&& (this.getCversion() == castOther.getCversion());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNnotaAbono() == null ? 0 : this.getNnotaAbono()
						.hashCode());
		result = 37 * result + this.getCformulario();
		result = 37 * result + this.getCversion();
		return result;
	}

}
