package sv.global.colas.entities;
// Generated 11-20-2014 03:17:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EdDeclaraciones generated by hbm2java
 */
@Entity
@Table(name="ED_DECLARACIONES"
    ,schema="EDADEPUDOC"
)
public class EdDeclaraciones  implements java.io.Serializable {


     private Long CDeclaracion;
     private TbFormulariosVersiones tbFormulariosVersiones;
     private TbUnidadRecep tbUnidadRecep;
     private String NFolio;
     private String NFolioModifica;
     private String NNotaAbono;
     private Date fpDeclaracion;
     private Date FPresentacion;
     private Integer BActiva;
     private String MEstado;
     private Integer BExtemporanea;
     private Double VTotalPago;
     private Double VTotalDevolver;
     private String MProceso;
     private String CMoneda;
     private String SXml;
     private String CUsuario;
     private Date FIngreso;
     private String SUbicacion;
     private String nit;
     private Integer BModificatoria;
     private String MFormato;
     private String MIngreso;
     private Date FInactivacion;
     private String CUsuInactiva;
     private String MLiqImpuesto;
     private String CCodigoUnico;
     
public EdDeclaraciones() {

}
   
     @Id 

    
    @Column(name="C_DECLARACION", unique=true, nullable=false, precision=18, scale=0)
    public Long getCDeclaracion() {
        return this.CDeclaracion;
    }
    
    public void setCDeclaracion(Long CDeclaracion) {
        this.CDeclaracion = CDeclaracion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="C_FORMULARIO", referencedColumnName="C_FORMULARIO", nullable=false), 
        @JoinColumn(name="C_VERSION", referencedColumnName="C_VERSION", nullable=false) } )
    public TbFormulariosVersiones getTbFormulariosVersiones() {
        return this.tbFormulariosVersiones;
    }
    
    public void setTbFormulariosVersiones(TbFormulariosVersiones tbFormulariosVersiones) {
        this.tbFormulariosVersiones = tbFormulariosVersiones;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_UNIDAD_RECEPTORA")
    public TbUnidadRecep getTbUnidadRecep() {
        return this.tbUnidadRecep;
    }
    
    public void setTbUnidadRecep(TbUnidadRecep tbUnidadRecep) {
        this.tbUnidadRecep = tbUnidadRecep;
    }

    
    @Column(name="N_FOLIO", length=14)
    public String getNFolio() {
        return this.NFolio;
    }
    
    public void setNFolio(String NFolio) {
        this.NFolio = NFolio;
    }

    
    @Column(name="N_FOLIO_MODIFICA", length=14)
    public String getNFolioModifica() {
        return this.NFolioModifica;
    }
    
    public void setNFolioModifica(String NFolioModifica) {
        this.NFolioModifica = NFolioModifica;
    }

    
    @Column(name="N_NOTA_ABONO", length=12)
    public String getNNotaAbono() {
        return this.NNotaAbono;
    }
    
    public void setNNotaAbono(String NNotaAbono) {
        this.NNotaAbono = NNotaAbono;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FP_DECLARACION")
    public Date getFpDeclaracion() {
        return this.fpDeclaracion;
    }
    
    public void setFpDeclaracion(Date fpDeclaracion) {
        this.fpDeclaracion = fpDeclaracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_PRESENTACION")
    public Date getFPresentacion() {
        return this.FPresentacion;
    }
    
    public void setFPresentacion(Date FPresentacion) {
        this.FPresentacion = FPresentacion;
    }

    
    @Column(name="B_ACTIVA", nullable=false, precision=1, scale=0)
    public Integer getBActiva() {
        return this.BActiva;
    }
    
    public void setBActiva(Integer BActiva) {
        this.BActiva = BActiva;
    }

    
    @Column(name="M_ESTADO", nullable=false, length=3)
    public String getMEstado() {
        return this.MEstado;
    }
    
    public void setMEstado(String MEstado) {
        this.MEstado = MEstado;
    }

    
    @Column(name="B_EXTEMPORANEA", nullable=false, precision=1, scale=0)
    public Integer getBExtemporanea() {
        return this.BExtemporanea;
    }
    
    public void setBExtemporanea(Integer BExtemporanea) {
        this.BExtemporanea = BExtemporanea;
    }

    
    @Column(name="V_TOTAL_PAGO", nullable=false, precision=18)
    public Double getVTotalPago() {
        return this.VTotalPago;
    }
    
    public void setVTotalPago(Double VTotalPago) {
        this.VTotalPago = VTotalPago;
    }

    
    @Column(name="V_TOTAL_DEVOLVER", nullable=false, precision=18)
    public Double getVTotalDevolver() {
        return this.VTotalDevolver;
    }
    
    public void setVTotalDevolver(Double VTotalDevolver) {
        this.VTotalDevolver = VTotalDevolver;
    }

    
    @Column(name="M_PROCESO", nullable=false, length=2)
    public String getMProceso() {
        return this.MProceso;
    }
    
    public void setMProceso(String MProceso) {
        this.MProceso = MProceso;
    }

    
    @Column(name="C_MONEDA", nullable=false, length=2)
    public String getCMoneda() {
        return this.CMoneda;
    }
    
    public void setCMoneda(String CMoneda) {
        this.CMoneda = CMoneda;
    }

    
    @Column(name="S_XML", length=4000)
    public String getSXml() {
        return this.SXml;
    }
    
    public void setSXml(String SXml) {
        this.SXml = SXml;
    }

    
    @Column(name="C_USUARIO", nullable=false, length=40)
    public String getCUsuario() {
        return this.CUsuario;
    }
    
    public void setCUsuario(String CUsuario) {
        this.CUsuario = CUsuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="F_INGRESO", nullable=false)
    public Date getFIngreso() {
        return this.FIngreso;
    }
    
    public void setFIngreso(Date FIngreso) {
        this.FIngreso = FIngreso;
    }

    
    @Column(name="S_UBICACION", length=1000)
    public String getSUbicacion() {
        return this.SUbicacion;
    }
    
    public void setSUbicacion(String SUbicacion) {
        this.SUbicacion = SUbicacion;
    }

    
    @Column(name="NIT", length=14)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

    
    @Column(name="B_MODIFICATORIA", nullable=false, precision=1, scale=0)
    public Integer getBModificatoria() {
        return this.BModificatoria;
    }
    
    public void setBModificatoria(Integer BModificatoria) {
        this.BModificatoria = BModificatoria;
    }

    
    @Column(name="M_FORMATO", length=1)
    public String getMFormato() {
        return this.MFormato;
    }
    
    public void setMFormato(String MFormato) {
        this.MFormato = MFormato;
    }

    
    @Column(name="M_INGRESO", length=1)
    public String getMIngreso() {
        return this.MIngreso;
    }
    
    public void setMIngreso(String MIngreso) {
        this.MIngreso = MIngreso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="F_INACTIVACION")
    public Date getFInactivacion() {
        return this.FInactivacion;
    }
    
    public void setFInactivacion(Date FInactivacion) {
        this.FInactivacion = FInactivacion;
    }

    
    @Column(name="C_USU_INACTIVA", length=30)
    public String getCUsuInactiva() {
        return this.CUsuInactiva;
    }
    
    public void setCUsuInactiva(String CUsuInactiva) {
        this.CUsuInactiva = CUsuInactiva;
    }

    
    @Column(name="M_LIQ_IMPUESTO", length=1)
    public String getMLiqImpuesto() {
        return this.MLiqImpuesto;
    }
    
    public void setMLiqImpuesto(String MLiqImpuesto) {
        this.MLiqImpuesto = MLiqImpuesto;
    }

    
    @Column(name="C_CODIGO_UNICO", length=12)
    public String getCCodigoUnico() {
        return this.CCodigoUnico;
    }
    
    public void setCCodigoUnico(String CCodigoUnico) {
        this.CCodigoUnico = CCodigoUnico;
    }


    /*@OneToOne(fetch=FetchType.LAZY, mappedBy="edDeclaraciones")
    public EdSolEquiposElectronicos getEdSolEquiposElectronicos() {
        return this.edSolEquiposElectronicos;
    }
    
    public void setEdSolEquiposElectronicos(EdSolEquiposElectronicos edSolEquiposElectronicos) {
        this.edSolEquiposElectronicos = edSolEquiposElectronicos;
    }*/



    /*@OneToOne(fetch=FetchType.LAZY, mappedBy="edDeclaraciones")
    public EdAmnistiaFileDet getEdAmnistiaFileDet() {
        return this.edAmnistiaFileDet;
    }
    
    public void setEdAmnistiaFileDet(EdAmnistiaFileDet edAmnistiaFileDet) {
        this.edAmnistiaFileDet = edAmnistiaFileDet;
    }*/

    /*@OneToMany(fetch=FetchType.LAZY, mappedBy="edDeclaraciones")
    public Set<DcPatDetBieninm> getDcPatDetBieninms() {
        return this.dcPatDetBieninms;
    }
    
    public void setDcPatDetBieninms(Set<DcPatDetBieninm> dcPatDetBieninms) {
        this.dcPatDetBieninms = dcPatDetBieninms;
    }*/


    /*@OneToOne(fetch=FetchType.LAZY, mappedBy="edDeclaraciones")
    public EdPatente getEdPatente() {
        return this.edPatente;
    }
    
    public void setEdPatente(EdPatente edPatente) {
        this.edPatente = edPatente;
    }*/

    /*@OneToMany(fetch=FetchType.LAZY, mappedBy="edDeclaraciones")
    public Set<EdDeclaracionesAud> getEdDeclaracionesAuds() {
        return this.edDeclaracionesAuds;
    }
    
    public void setEdDeclaracionesAuds(Set<EdDeclaracionesAud> edDeclaracionesAuds) {
        this.edDeclaracionesAuds = edDeclaracionesAuds;
    }*/

    /*@OneToOne(fetch=FetchType.LAZY, mappedBy="edDeclaraciones")
    public DcPrimeraMatric getDcPrimeraMatric() {
        return this.dcPrimeraMatric;
    }
    
    public void setDcPrimeraMatric(DcPrimeraMatric dcPrimeraMatric) {
        this.dcPrimeraMatric = dcPrimeraMatric;
    }*/




}


