package sv.global.colas.entities;

// Generated Dec 12, 2007 1:25:05 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EdLoteCdt generated by hbm2java
 */
@Entity
@Table(name = "ED_LOTE_CDT", schema = "EDADEPUDOC")
public class EdLoteCdt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2647710362686868086L;
	private Long nlote;
	private EdDetalleNota edDetalleNota;
	private Integer ndocumentos;
	private Integer ncorrelativo;
	private String scarpeta;
	private String cusuario;
	private Date fhingreso;

	public EdLoteCdt() {
	}

	public EdLoteCdt(Long nlote, Integer ndocumentos, Integer ncorrelativo,
			String scarpeta, String cusuario, Date fhingreso) {
		this.nlote = nlote;
		this.ndocumentos = ndocumentos;
		this.ncorrelativo = ncorrelativo;
		this.scarpeta = scarpeta;
		this.cusuario = cusuario;
		this.fhingreso = fhingreso;
	}

	public EdLoteCdt(Long nlote, EdDetalleNota edDetalleNota,
			Integer ndocumentos, Integer ncorrelativo, String scarpeta,
			String cusuario, Date fhingreso) {
		this.nlote = nlote;
		this.edDetalleNota = edDetalleNota;
		this.ndocumentos = ndocumentos;
		this.ncorrelativo = ncorrelativo;
		this.scarpeta = scarpeta;
		this.cusuario = cusuario;
		this.fhingreso = fhingreso;
	}

	@Id
	@Column(name = "N_LOTE", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getNlote() {
		return this.nlote;
	}

	public void setNlote(Long nlote) {
		this.nlote = nlote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "N_NOTA_ABONO", referencedColumnName = "N_NOTA_ABONO"),
			@JoinColumn(name = "C_FORMULARIO", referencedColumnName = "C_FORMULARIO"),
			@JoinColumn(name = "C_VERSION", referencedColumnName = "C_VERSION") })
	public EdDetalleNota getEdDetalleNota() {
		return this.edDetalleNota;
	}

	public void setEdDetalleNota(EdDetalleNota edDetalleNota) {
		this.edDetalleNota = edDetalleNota;
	}

	@Column(name = "N_DOCUMENTOS", nullable = false, precision = 5, scale = 0)
	public Integer getNdocumentos() {
		return this.ndocumentos;
	}

	public void setNdocumentos(Integer ndocumentos) {
		this.ndocumentos = ndocumentos;
	}

	@Column(name = "N_CORRELATIVO", nullable = false, precision = 5, scale = 0)
	public Integer getNcorrelativo() {
		return this.ncorrelativo;
	}

	public void setNcorrelativo(Integer ncorrelativo) {
		this.ncorrelativo = ncorrelativo;
	}

	@Column(name = "S_CARPETA", nullable = false, length = 50)
	public String getScarpeta() {
		return this.scarpeta;
	}

	public void setScarpeta(String scarpeta) {
		this.scarpeta = scarpeta;
	}

	@Column(name = "C_USUARIO", nullable = false, length = 30)
	public String getCusuario() {
		return this.cusuario;
	}

	public void setCusuario(String cusuario) {
		this.cusuario = cusuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_INGRESO", nullable = false, length = 7)
	public Date getFhingreso() {
		return this.fhingreso;
	}

	public void setFhingreso(Date fhingreso) {
		this.fhingreso = fhingreso;
	}

}
