package sv.global.colas.entities;
// Generated 11-20-2014 03:17:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EdNotaAbono generated by hbm2java
 */
@Entity
@Table(name="ED_NOTA_ABONO"
    ,schema="EDADEPUDOC"
)
public class EdNotaAbono  implements java.io.Serializable {


     private String NNotaAbono;
     private TbUnidadRecep tbUnidadRecep;
     private TbMoneda tbMoneda;
     private EdPlanilla edPlanilla;
     private String CUsuario;
     private Double VTotalAbonado;
     private Date FRecepCumplim;
     private Integer NDgiDocNota;
     private Double VDgiMonNota;
     private Integer NDgiDocDigit;
     private Double VDgiMonDig;
     private Date fhActualizacion;
     private Date fhIngreso;
     private Long ILote;
     private Integer BEnviado;
     private Integer BCuadreNota;
     private Integer BStatusNota;
     private Date fhCierreLote;
     private String CUsuarioCierre;
     private String CUsuarioSuperv;
     private Date fhSupervision;
     private String SNotaSuperv;
     private Integer BRecibido;
     private String CUsuarioRecibe;
     private Date fhRecibeCtrlDoc;
     private String MFormato;
     private String CUsuarioEnvia;
     private Date fhEnvioCtrlDoc;
     private String SHostFolder;
     private Long NDocPlaDgii;
     private Double VMonPlaDgii;
     private String SObservacion;
     private Long ITecnico;
     private String MFormulario;
     private Integer BVerificaCuenta;
     private String MFormularioAlterno;
     private Set<EdDetalleNota> edDetalleNotas = new HashSet<EdDetalleNota>(0);

public EdNotaAbono() {

}
   
     @Id 

    
    @Column(name="N_NOTA_ABONO", unique=true, nullable=false, length=12)
    public String getNNotaAbono() {
        return this.NNotaAbono;
    }
    
    public void setNNotaAbono(String NNotaAbono) {
        this.NNotaAbono = NNotaAbono;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_UNIDAD_RECEP")
    public TbUnidadRecep getTbUnidadRecep() {
        return this.tbUnidadRecep;
    }
    
    public void setTbUnidadRecep(TbUnidadRecep tbUnidadRecep) {
        this.tbUnidadRecep = tbUnidadRecep;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_MONEDA", nullable=false)
    public TbMoneda getTbMoneda() {
        return this.tbMoneda;
    }
    
    public void setTbMoneda(TbMoneda tbMoneda) {
        this.tbMoneda = tbMoneda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="N_PLANILLA", nullable=false)
    public EdPlanilla getEdPlanilla() {
        return this.edPlanilla;
    }
    
    public void setEdPlanilla(EdPlanilla edPlanilla) {
        this.edPlanilla = edPlanilla;
    }

    
    @Column(name="C_USUARIO", nullable=false, length=30)
    public String getCUsuario() {
        return this.CUsuario;
    }
    
    public void setCUsuario(String CUsuario) {
        this.CUsuario = CUsuario;
    }

    
    @Column(name="V_TOTAL_ABONADO", precision=12)
    public Double getVTotalAbonado() {
        return this.VTotalAbonado;
    }
    
    public void setVTotalAbonado(Double VTotalAbonado) {
        this.VTotalAbonado = VTotalAbonado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_RECEP_CUMPLIM", length=7)
    public Date getFRecepCumplim() {
        return this.FRecepCumplim;
    }
    
    public void setFRecepCumplim(Date FRecepCumplim) {
        this.FRecepCumplim = FRecepCumplim;
    }

    
    @Column(name="N_DGI_DOC_NOTA", precision=5, scale=0)
    public Integer getNDgiDocNota() {
        return this.NDgiDocNota;
    }
    
    public void setNDgiDocNota(Integer NDgiDocNota) {
        this.NDgiDocNota = NDgiDocNota;
    }

    
    @Column(name="V_DGI_MON_NOTA", precision=12)
    public Double getVDgiMonNota() {
        return this.VDgiMonNota;
    }
    
    public void setVDgiMonNota(Double VDgiMonNota) {
        this.VDgiMonNota = VDgiMonNota;
    }

    
    @Column(name="N_DGI_DOC_DIGIT", precision=5, scale=0)
    public Integer getNDgiDocDigit() {
        return this.NDgiDocDigit;
    }
    
    public void setNDgiDocDigit(Integer NDgiDocDigit) {
        this.NDgiDocDigit = NDgiDocDigit;
    }

    
    @Column(name="V_DGI_MON_DIG", precision=12)
    public Double getVDgiMonDig() {
        return this.VDgiMonDig;
    }
    
    public void setVDgiMonDig(Double VDgiMonDig) {
        this.VDgiMonDig = VDgiMonDig;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FH_ACTUALIZACION", length=7)
    public Date getFhActualizacion() {
        return this.fhActualizacion;
    }
    
    public void setFhActualizacion(Date fhActualizacion) {
        this.fhActualizacion = fhActualizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FH_INGRESO", nullable=false, length=7)
    public Date getFhIngreso() {
        return this.fhIngreso;
    }
    
    public void setFhIngreso(Date fhIngreso) {
        this.fhIngreso = fhIngreso;
    }

    
    @Column(name="I_LOTE", precision=10, scale=0)
    public Long getILote() {
        return this.ILote;
    }
    
    public void setILote(Long ILote) {
        this.ILote = ILote;
    }

    
    @Column(name="B_ENVIADO", precision=1, scale=0)
    public Integer getBEnviado() {
        return this.BEnviado;
    }
    
    public void setBEnviado(Integer BEnviado) {
        this.BEnviado = BEnviado;
    }

    
    @Column(name="B_CUADRE_NOTA", precision=1, scale=0)
    public Integer getBCuadreNota() {
        return this.BCuadreNota;
    }
    
    public void setBCuadreNota(Integer BCuadreNota) {
        this.BCuadreNota = BCuadreNota;
    }

    
    @Column(name="B_STATUS_NOTA", nullable=false, precision=2, scale=0)
    public Integer getBStatusNota() {
        return this.BStatusNota;
    }
    
    public void setBStatusNota(Integer BStatusNota) {
        this.BStatusNota = BStatusNota;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FH_CIERRE_LOTE", length=7)
    public Date getFhCierreLote() {
        return this.fhCierreLote;
    }
    
    public void setFhCierreLote(Date fhCierreLote) {
        this.fhCierreLote = fhCierreLote;
    }

    
    @Column(name="C_USUARIO_CIERRE", length=40)
    public String getCUsuarioCierre() {
        return this.CUsuarioCierre;
    }
    
    public void setCUsuarioCierre(String CUsuarioCierre) {
        this.CUsuarioCierre = CUsuarioCierre;
    }

    
    @Column(name="C_USUARIO_SUPERV", length=40)
    public String getCUsuarioSuperv() {
        return this.CUsuarioSuperv;
    }
    
    public void setCUsuarioSuperv(String CUsuarioSuperv) {
        this.CUsuarioSuperv = CUsuarioSuperv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FH_SUPERVISION", length=7)
    public Date getFhSupervision() {
        return this.fhSupervision;
    }
    
    public void setFhSupervision(Date fhSupervision) {
        this.fhSupervision = fhSupervision;
    }

    
    @Column(name="S_NOTA_SUPERV")
    public String getSNotaSuperv() {
        return this.SNotaSuperv;
    }
    
    public void setSNotaSuperv(String SNotaSuperv) {
        this.SNotaSuperv = SNotaSuperv;
    }

    
    @Column(name="B_RECIBIDO", precision=1, scale=0)
    public Integer getBRecibido() {
        return this.BRecibido;
    }
    
    public void setBRecibido(Integer BRecibido) {
        this.BRecibido = BRecibido;
    }

    
    @Column(name="C_USUARIO_RECIBE", length=40)
    public String getCUsuarioRecibe() {
        return this.CUsuarioRecibe;
    }
    
    public void setCUsuarioRecibe(String CUsuarioRecibe) {
        this.CUsuarioRecibe = CUsuarioRecibe;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FH_RECIBE_CTRL_DOC", length=7)
    public Date getFhRecibeCtrlDoc() {
        return this.fhRecibeCtrlDoc;
    }
    
    public void setFhRecibeCtrlDoc(Date fhRecibeCtrlDoc) {
        this.fhRecibeCtrlDoc = fhRecibeCtrlDoc;
    }

    
    @Column(name="M_FORMATO", length=1)
    public String getMFormato() {
        return this.MFormato;
    }
    
    public void setMFormato(String MFormato) {
        this.MFormato = MFormato;
    }

    
    @Column(name="C_USUARIO_ENVIA", length=40)
    public String getCUsuarioEnvia() {
        return this.CUsuarioEnvia;
    }
    
    public void setCUsuarioEnvia(String CUsuarioEnvia) {
        this.CUsuarioEnvia = CUsuarioEnvia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FH_ENVIO_CTRL_DOC", length=7)
    public Date getFhEnvioCtrlDoc() {
        return this.fhEnvioCtrlDoc;
    }
    
    public void setFhEnvioCtrlDoc(Date fhEnvioCtrlDoc) {
        this.fhEnvioCtrlDoc = fhEnvioCtrlDoc;
    }

    
    @Column(name="S_HOST_FOLDER", length=50)
    public String getSHostFolder() {
        return this.SHostFolder;
    }
    
    public void setSHostFolder(String SHostFolder) {
        this.SHostFolder = SHostFolder;
    }

    
    @Column(name="N_DOC_PLA_DGII", precision=22, scale=0)
    public Long getNDocPlaDgii() {
        return this.NDocPlaDgii;
    }
    
    public void setNDocPlaDgii(Long NDocPlaDgii) {
        this.NDocPlaDgii = NDocPlaDgii;
    }

    
    @Column(name="V_MON_PLA_DGII", precision=12)
    public Double getVMonPlaDgii() {
        return this.VMonPlaDgii;
    }
    
    public void setVMonPlaDgii(Double VMonPlaDgii) {
        this.VMonPlaDgii = VMonPlaDgii;
    }

    
    @Column(name="S_OBSERVACION")
    public String getSObservacion() {
        return this.SObservacion;
    }
    
    public void setSObservacion(String SObservacion) {
        this.SObservacion = SObservacion;
    }

    
    @Column(name="I_TECNICO", precision=10, scale=0)
    public Long getITecnico() {
        return this.ITecnico;
    }
    
    public void setITecnico(Long ITecnico) {
        this.ITecnico = ITecnico;
    }

    
    @Column(name="M_FORMULARIO", length=1)
    public String getMFormulario() {
        return this.MFormulario;
    }
    
    public void setMFormulario(String MFormulario) {
        this.MFormulario = MFormulario;
    }

    
    @Column(name="B_VERIFICA_CUENTA", precision=1, scale=0)
    public Integer getBVerificaCuenta() {
        return this.BVerificaCuenta;
    }
    
    public void setBVerificaCuenta(Integer BVerificaCuenta) {
        this.BVerificaCuenta = BVerificaCuenta;
    }

    
    @Column(name="M_FORMULARIO_ALTERNO", length=3)
    public String getMFormularioAlterno() {
        return this.MFormularioAlterno;
    }
    
    public void setMFormularioAlterno(String MFormularioAlterno) {
        this.MFormularioAlterno = MFormularioAlterno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="edNotaAbono")
    public Set<EdDetalleNota> getEdDetalleNotas() {
        return this.edDetalleNotas;
    }
    
    public void setEdDetalleNotas(Set<EdDetalleNota> edDetalleNotas) {
        this.edDetalleNotas = edDetalleNotas;
    }




}


