package sv.global.colas.entities;
// Generated 11-20-2014 03:17:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RcRuc generated by hbm2java
 */
@Entity
@Table(name="RC_RUC"
    ,schema="RUC"
)
public class RcRuc  implements java.io.Serializable {


     private String nit;
     private TbTipoContrib tbTipoContrib;
     private TbTermino tbTermino;
     private TbPais tbPais;
     private TbMunicipio tbMunicipio;
     private TbImportancia tbImportancia;
     private TbAdmTrib tbAdmTrib;
     private String s1apeRasoc;
     private String s2apeAbrev;
     private String SNombres;
     private Date FNacConst;
     private Integer BDomiciliado;
     private Date FTermino;
     private Integer BInteresFiscal;
     private String MSexo;
     private Integer BImportador;
     private Double VCapitalSoc;
     private String BActivo;
     private Integer BAlerta;
     
     //private Set<RcTramite> rcTramites = new HashSet<RcTramite>(0);
     
public RcRuc() {

}
   
     @Id 

    
    @Column(name="NIT", unique=true, nullable=false, length=14)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="C_CLASE", referencedColumnName="C_CLASE", nullable=false), 
        @JoinColumn(name="C_TIPO", referencedColumnName="C_TIPO", nullable=false) } )
    public TbTipoContrib getTbTipoContrib() {
        return this.tbTipoContrib;
    }
    
    public void setTbTipoContrib(TbTipoContrib tbTipoContrib) {
        this.tbTipoContrib = tbTipoContrib;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_TERMINO", nullable=false)
    public TbTermino getTbTermino() {
        return this.tbTermino;
    }
    
    public void setTbTermino(TbTermino tbTermino) {
        this.tbTermino = tbTermino;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_PAIS", nullable=false)
    public TbPais getTbPais() {
        return this.tbPais;
    }
    
    public void setTbPais(TbPais tbPais) {
        this.tbPais = tbPais;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="C_DEPARTAMENTO", referencedColumnName="C_DEPARTAMENTO", nullable=false), 
        @JoinColumn(name="C_MUNICIPIO", referencedColumnName="C_MUNICIPIO", nullable=false) } )
    public TbMunicipio getTbMunicipio() {
        return this.tbMunicipio;
    }
    
    public void setTbMunicipio(TbMunicipio tbMunicipio) {
        this.tbMunicipio = tbMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_IMPORTANCIA", nullable=false)
    public TbImportancia getTbImportancia() {
        return this.tbImportancia;
    }
    
    public void setTbImportancia(TbImportancia tbImportancia) {
        this.tbImportancia = tbImportancia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_ADM_TRIB", nullable=false)
    public TbAdmTrib getTbAdmTrib() {
        return this.tbAdmTrib;
    }
    
    public void setTbAdmTrib(TbAdmTrib tbAdmTrib) {
        this.tbAdmTrib = tbAdmTrib;
    }

    
    @Column(name="S_1APE_RASOC", nullable=false, length=100)
    public String getS1apeRasoc() {
        return this.s1apeRasoc;
    }
    
    public void setS1apeRasoc(String s1apeRasoc) {
        this.s1apeRasoc = s1apeRasoc;
    }

    
    @Column(name="S_2APE_ABREV", length=100)
    public String getS2apeAbrev() {
        return this.s2apeAbrev;
    }
    
    public void setS2apeAbrev(String s2apeAbrev) {
        this.s2apeAbrev = s2apeAbrev;
    }

    
    @Column(name="S_NOMBRES", length=40)
    public String getSNombres() {
        return this.SNombres;
    }
    
    public void setSNombres(String SNombres) {
        this.SNombres = SNombres;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_NAC_CONST", nullable=false, length=7)
    public Date getFNacConst() {
        return this.FNacConst;
    }
    
    public void setFNacConst(Date FNacConst) {
        this.FNacConst = FNacConst;
    }

    
    @Column(name="B_DOMICILIADO", nullable=false, precision=1, scale=0)
    public Integer getBDomiciliado() {
        return this.BDomiciliado;
    }
    
    public void setBDomiciliado(Integer BDomiciliado) {
        this.BDomiciliado = BDomiciliado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="F_TERMINO", length=7)
    public Date getFTermino() {
        return this.FTermino;
    }
    
    public void setFTermino(Date FTermino) {
        this.FTermino = FTermino;
    }

    
    @Column(name="B_INTERES_FISCAL", nullable=false, precision=1, scale=0)
    public Integer getBInteresFiscal() {
        return this.BInteresFiscal;
    }
    
    public void setBInteresFiscal(Integer BInteresFiscal) {
        this.BInteresFiscal = BInteresFiscal;
    }

    
    @Column(name="M_SEXO", length=1)
    public String getMSexo() {
        return this.MSexo;
    }
    
    public void setMSexo(String MSexo) {
        this.MSexo = MSexo;
    }

    
    @Column(name="B_IMPORTADOR", nullable=false, precision=1, scale=0)
    public Integer getBImportador() {
        return this.BImportador;
    }
    
    public void setBImportador(Integer BImportador) {
        this.BImportador = BImportador;
    }

    
    @Column(name="V_CAPITAL_SOC", precision=13)
    public Double getVCapitalSoc() {
        return this.VCapitalSoc;
    }
    
    public void setVCapitalSoc(Double VCapitalSoc) {
        this.VCapitalSoc = VCapitalSoc;
    }

    
    @Column(name="B_ACTIVO", nullable=false, length=1)
    public String getBActivo() {
        return this.BActivo;
    }
    
    public void setBActivo(String BActivo) {
        this.BActivo = BActivo;
    }

    
    @Column(name="B_ALERTA", precision=1, scale=0)
    public Integer getBAlerta() {
        return this.BAlerta;
    }
    
    public void setBAlerta(Integer BAlerta) {
        this.BAlerta = BAlerta;
    }






}


