package sv.global.colas.entities;

// Generated Dec 12, 2007 1:25:05 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RcTramiteId generated by hbm2java
 */
@Embeddable
public class RcTramiteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4978640372965852044L;
	private String nfolio;
	private String ctramite;
	private String nit;

	public RcTramiteId() {
	}

	public RcTramiteId(String nfolio, String ctramite, String nit) {
		this.nfolio = nfolio;
		this.ctramite = ctramite;
		this.nit = nit;
	}

	@Column(name = "N_FOLIO", nullable = false, length = 12)
	public String getNfolio() {
		return this.nfolio;
	}

	public void setNfolio(String nfolio) {
		this.nfolio = nfolio;
	}

	@Column(name = "C_TRAMITE", nullable = false, length = 3)
	public String getCtramite() {
		return this.ctramite;
	}

	public void setCtramite(String ctramite) {
		this.ctramite = ctramite;
	}

	@Column(name = "NIT", nullable = false, length = 14)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RcTramiteId))
			return false;
		RcTramiteId castOther = (RcTramiteId) other;

		return ((this.getNfolio() == castOther.getNfolio()) || (this
				.getNfolio() != null
				&& castOther.getNfolio() != null && this.getNfolio().equals(
				castOther.getNfolio())))
				&& ((this.getCtramite() == castOther.getCtramite()) || (this
						.getCtramite() != null
						&& castOther.getCtramite() != null && this
						.getCtramite().equals(castOther.getCtramite())))
				&& ((this.getNit() == castOther.getNit()) || (this.getNit() != null
						&& castOther.getNit() != null && this.getNit().equals(
						castOther.getNit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNfolio() == null ? 0 : this.getNfolio().hashCode());
		result = 37 * result
				+ (getCtramite() == null ? 0 : this.getCtramite().hashCode());
		result = 37 * result
				+ (getNit() == null ? 0 : this.getNit().hashCode());
		return result;
	}

}
