package sv.global.colas.entities;

// Generated Dec 10, 2007 4:52:21 PM by Hibernate Tools 3.2.0.beta7

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAdmTrib generated by hbm2java
 */
@Entity
@Table(name = "TB_ADM_TRIB", schema = "CATALOGOS", uniqueConstraints = {})
public class TbAdmTrib implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 2482953551918413450L;

	private String cadmTrib;

	private String cusuario;

	private String dadmTrib;

	private Date fhingreso;

	private Boolean bstatus;

	private Boolean bdefault;

	private Boolean bregion;

	private Long ninventario;

	private Boolean bctrlDocum;

	private String sfuncResp;

	private String subicFunc;

	private Integer blogo;

	private Integer bconstancia;

	private String sarchivoFirma;

	private String subicGeograf;

	

	private Set<RcRuc> rcRucs = new HashSet<RcRuc>(0);

	
	private Set<RcTramite> rcTramites = new HashSet<RcTramite>(0);

	

	// Constructors

	/** default constructor */
	public TbAdmTrib() {
	}
	public TbAdmTrib(String cadmTrib){
		 this.cadmTrib = cadmTrib;
		
	}
	
	public TbAdmTrib(String cadmTrib,String dadmTrib){
		 this.cadmTrib = cadmTrib;
		 this.dadmTrib = dadmTrib;
		
	}

	/** minimal constructor */
	public TbAdmTrib(String cadmTrib, String cusuario, String dadmTrib,
			Date fhingreso, Boolean bstatus, Boolean bdefault, Boolean bregion,
			Long ninventario, Boolean bctrlDocum, Integer blogo,
			Integer bconstancia) {
		this.cadmTrib = cadmTrib;
		this.cusuario = cusuario;
		this.dadmTrib = dadmTrib;
		this.fhingreso = fhingreso;
		this.bstatus = bstatus;
		this.bdefault = bdefault;
		this.bregion = bregion;
		this.ninventario = ninventario;
		this.bctrlDocum = bctrlDocum;
		this.blogo = blogo;
		this.bconstancia = bconstancia;
	}

	/** full constructor */
	public TbAdmTrib(String cadmTrib, String cusuario, String dadmTrib,
			Date fhingreso, Boolean bstatus, Boolean bdefault, Boolean bregion,
			Long ninventario, Boolean bctrlDocum, String sfuncResp,
			String subicFunc, Integer blogo, Integer bconstancia,
			String sarchivoFirma, String subicGeograf,
			Set<RcRuc> rcRucs,
			 Set<RcTramite> rcTramites
			 ) {
		this.cadmTrib = cadmTrib;
		this.cusuario = cusuario;
		this.dadmTrib = dadmTrib;
		this.fhingreso = fhingreso;
		this.bstatus = bstatus;
		this.bdefault = bdefault;
		this.bregion = bregion;
		this.ninventario = ninventario;
		this.bctrlDocum = bctrlDocum;
		this.sfuncResp = sfuncResp;
		this.subicFunc = subicFunc;
		this.blogo = blogo;
		this.bconstancia = bconstancia;
		this.sarchivoFirma = sarchivoFirma;
		this.subicGeograf = subicGeograf;		
		this.rcRucs = rcRucs;		
		this.rcTramites = rcTramites;
	 
	}

	// Property accessors
	@Id
	@Column(name = "C_ADM_TRIB", unique = true, nullable = false, insertable = true, updatable = true, length = 2)
	public String getCadmTrib() {
		return this.cadmTrib;
	}

	public void setCadmTrib(String cadmTrib) {
		this.cadmTrib = cadmTrib;
	}

	@Column(name = "C_USUARIO", unique = false, nullable = false, insertable = true, updatable = true, length = 30)
	public String getCusuario() {
		return this.cusuario;
	}

	public void setCusuario(String cusuario) {
		this.cusuario = cusuario;
	}

	@Column(name = "D_ADM_TRIB", unique = false, nullable = false, insertable = true, updatable = true)
	public String getDadmTrib() {
		return this.dadmTrib;
	}

	public void setDadmTrib(String dadmTrib) {
		this.dadmTrib = dadmTrib;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_INGRESO", unique = false, nullable = false, insertable = true, updatable = true, length = 7)
	public Date getFhingreso() {
		return this.fhingreso;
	}

	public void setFhingreso(Date fhingreso) {
		this.fhingreso = fhingreso;
	}

	@Column(name = "B_STATUS", unique = false, nullable = false, insertable = true, updatable = true, precision = 1, scale = 0)
	public Boolean getBstatus() {
		return this.bstatus;
	}

	public void setBstatus(Boolean bstatus) {
		this.bstatus = bstatus;
	}

	@Column(name = "B_DEFAULT", unique = false, nullable = false, insertable = true, updatable = true, precision = 1, scale = 0)
	public Boolean getBdefault() {
		return this.bdefault;
	}

	public void setBdefault(Boolean bdefault) {
		this.bdefault = bdefault;
	}

	@Column(name = "B_REGION", unique = false, nullable = false, insertable = true, updatable = true, precision = 1, scale = 0)
	public Boolean getBregion() {
		return this.bregion;
	}

	public void setBregion(Boolean bregion) {
		this.bregion = bregion;
	}

	@Column(name = "N_INVENTARIO", unique = false, nullable = false, insertable = true, updatable = true, precision = 10, scale = 0)
	public Long getNinventario() {
		return this.ninventario;
	}

	public void setNinventario(Long ninventario) {
		this.ninventario = ninventario;
	}

	@Column(name = "B_CTRL_DOCUM", unique = false, nullable = false, insertable = true, updatable = true, precision = 1, scale = 0)
	public Boolean getBctrlDocum() {
		return this.bctrlDocum;
	}

	public void setBctrlDocum(Boolean bctrlDocum) {
		this.bctrlDocum = bctrlDocum;
	}

	@Column(name = "S_FUNC_RESP", unique = false, nullable = true, insertable = true, updatable = true, length = 60)
	public String getSfuncResp() {
		return this.sfuncResp;
	}

	public void setSfuncResp(String sfuncResp) {
		this.sfuncResp = sfuncResp;
	}

	@Column(name = "S_UBIC_FUNC", unique = false, nullable = true, insertable = true, updatable = true, length = 60)
	public String getSubicFunc() {
		return this.subicFunc;
	}

	public void setSubicFunc(String subicFunc) {
		this.subicFunc = subicFunc;
	}

	@Column(name = "B_LOGO", unique = false, nullable = false, insertable = true, updatable = true, precision = 1, scale = 0)
	public Integer getBlogo() {
		return this.blogo;
	}

	public void setBlogo(Integer blogo) {
		this.blogo = blogo;
	}

	@Column(name = "B_CONSTANCIA", unique = false, nullable = false, insertable = true, updatable = true, precision = 1, scale = 0)
	public Integer getBconstancia() {
		return this.bconstancia;
	}

	public void setBconstancia(Integer bconstancia) {
		this.bconstancia = bconstancia;
	}

	@Column(name = "S_ARCHIVO_FIRMA", unique = false, nullable = true, insertable = true, updatable = true, length = 70)
	public String getSarchivoFirma() {
		return this.sarchivoFirma;
	}

	public void setSarchivoFirma(String sarchivoFirma) {
		this.sarchivoFirma = sarchivoFirma;
	}

	@Column(name = "S_UBIC_GEOGRAF", unique = false, nullable = true, insertable = true, updatable = true, length = 70)
	public String getSubicGeograf() {
		return this.subicGeograf;
	}

	public void setSubicGeograf(String subicGeograf) {
		this.subicGeograf = subicGeograf;
	}

	

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "tbAdmTrib")	
	public Set<RcRuc> getRcRucs() {
		return this.rcRucs;
	}

	public void setRcRucs(Set<RcRuc> rcRucs) {
		this.rcRucs = rcRucs;
	}

	

	@OneToMany( fetch = FetchType.LAZY, mappedBy = "tbAdmTrib")	
	public Set<RcTramite> getRcTramites() {
		return this.rcTramites;
	}

	public void setRcTramites(Set<RcTramite> rcTramites) {
		this.rcTramites = rcTramites;
	}

}
