package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCamposExpresiones generated by hbm2java
 */
@Entity
@Table(name = "TB_CAMPOS_EXPRESIONES", schema = "CATALOGOS")
public class TbCamposExpresiones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long ccorrelativo;
	private TbFormulariosCampos tbFormulariosCampos;
	private String dexpresion;
	private String stipoDato;
	private String sexpresion;
	private String sinconsistencia;
	private String stabla;
	private String smensajeIncosistencia;
	private Integer bestado;
	private String cusuario;
	private Date fingreso;
	private Integer bcalcula;

	public TbCamposExpresiones() {
	}

	public TbCamposExpresiones(Long ccorrelativo,
			TbFormulariosCampos tbFormulariosCampos, String dexpresion) {
		this.ccorrelativo = ccorrelativo;
		this.tbFormulariosCampos = tbFormulariosCampos;
		this.dexpresion = dexpresion;
	}

	public TbCamposExpresiones(Long ccorrelativo,
			TbFormulariosCampos tbFormulariosCampos, String dexpresion,
			String stipoDato, String sexpresion, String sinconsistencia,
			String stabla, String smensajeIncosistencia, Integer bestado,
			String cusuario, Date fingreso, Integer bcalcula) {
		this.ccorrelativo = ccorrelativo;
		this.tbFormulariosCampos = tbFormulariosCampos;
		this.dexpresion = dexpresion;
		this.stipoDato = stipoDato;
		this.sexpresion = sexpresion;
		this.sinconsistencia = sinconsistencia;
		this.stabla = stabla;
		this.smensajeIncosistencia = smensajeIncosistencia;
		this.bestado = bestado;
		this.cusuario = cusuario;
		this.fingreso = fingreso;
		this.bcalcula = bcalcula;
	}

	@Id
	@Column(name = "C_CORRELATIVO", unique = true, nullable = false, precision = 6, scale = 0)
	public Long getCcorrelativo() {
		return this.ccorrelativo;
	}

	public void setCcorrelativo(Long ccorrelativo) {
		this.ccorrelativo = ccorrelativo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns( {
			@JoinColumn(name = "C_FORMULARIO", referencedColumnName = "C_FORMULARIO", nullable = false),
			@JoinColumn(name = "C_VERSION", referencedColumnName = "C_VERSION", nullable = false),
			@JoinColumn(name = "C_CAMPO", referencedColumnName = "C_CAMPO", nullable = false) })
	public TbFormulariosCampos getTbFormulariosCampos() {
		return this.tbFormulariosCampos;
	}

	public void setTbFormulariosCampos(TbFormulariosCampos tbFormulariosCampos) {
		this.tbFormulariosCampos = tbFormulariosCampos;
	}

	@Column(name = "D_EXPRESION", nullable = false, length = 80)
	public String getDexpresion() {
		return this.dexpresion;
	}

	public void setDexpresion(String dexpresion) {
		this.dexpresion = dexpresion;
	}

	@Column(name = "S_TIPO_DATO")
	public String getStipoDato() {
		return this.stipoDato;
	}

	public void setStipoDato(String stipoDato) {
		this.stipoDato = stipoDato;
	}

	@Column(name = "S_EXPRESION", length = 4000)
	public String getSexpresion() {
		return this.sexpresion;
	}

	public void setSexpresion(String sexpresion) {
		this.sexpresion = sexpresion;
	}

	@Column(name = "S_INCONSISTENCIA", length = 4000)
	public String getSinconsistencia() {
		return this.sinconsistencia;
	}

	public void setSinconsistencia(String sinconsistencia) {
		this.sinconsistencia = sinconsistencia;
	}

	@Column(name = "S_TABLA")
	public String getStabla() {
		return this.stabla;
	}

	public void setStabla(String stabla) {
		this.stabla = stabla;
	}

	@Column(name = "S_MENSAJE_INCOSISTENCIA", length = 4000)
	public String getSmensajeIncosistencia() {
		return this.smensajeIncosistencia;
	}

	public void setSmensajeIncosistencia(String smensajeIncosistencia) {
		this.smensajeIncosistencia = smensajeIncosistencia;
	}

	@Column(name = "B_ESTADO", precision = 1, scale = 0)
	public Integer getBestado() {
		return this.bestado;
	}

	public void setBestado(Integer bestado) {
		this.bestado = bestado;
	}

	@Column(name = "C_USUARIO", length = 40)
	public String getCusuario() {
		return this.cusuario;
	}

	public void setCusuario(String cusuario) {
		this.cusuario = cusuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_INGRESO", length = 7)
	public Date getFingreso() {
		return this.fingreso;
	}

	public void setFingreso(Date fingreso) {
		this.fingreso = fingreso;
	}

	@Column(name = "B_CALCULA", precision = 1, scale = 0)
	public Integer getBcalcula() {
		return this.bcalcula;
	}

	public void setBcalcula(Integer bcalcula) {
		this.bcalcula = bcalcula;
	}

}
