package sv.global.colas.entities;

// Generated 10-30-2009 11:58:06 AM by Hibernate Tools 3.2.4.GA

import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbEmail generated by hbm2java
 */
@Entity
@Table(name = "TB_EMAIL", schema = "DECLARACIONES")
public class TbEmail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 887742185223456660L;
	private String CEmail;
	private String SNombreCuenta;
	private String SEmailDe;
	private Blob XFormatoEmail;
	private String DAsunto;
	private String SSql;
	private String SSql1;
	private String SSql2;

	public TbEmail() {
	}

	public TbEmail(String CEmail, String SEmailDe, String DAsunto, String SSql) {
		this.CEmail = CEmail;
		this.SEmailDe = SEmailDe;
		this.DAsunto = DAsunto;
		this.SSql = SSql;
	}

	public TbEmail(String CEmail, String SNombreCuenta, String SEmailDe,
			Blob XFormatoEmail, String DAsunto, String SSql, String SSql1,
			String SSql2) {
		this.CEmail = CEmail;
		this.SNombreCuenta = SNombreCuenta;
		this.SEmailDe = SEmailDe;
		this.XFormatoEmail = XFormatoEmail;
		this.DAsunto = DAsunto;
		this.SSql = SSql;
		this.SSql1 = SSql1;
		this.SSql2 = SSql2;
	}

	@Id
	@Column(name = "C_EMAIL", nullable = false, length = 2)
	public String getCEmail() {
		return this.CEmail;
	}

	public void setCEmail(String CEmail) {
		this.CEmail = CEmail;
	}

	@Column(name = "S_NOMBRE_CUENTA", length = 100)
	public String getSNombreCuenta() {
		return this.SNombreCuenta;
	}

	public void setSNombreCuenta(String SNombreCuenta) {
		this.SNombreCuenta = SNombreCuenta;
	}

	@Column(name = "S_EMAIL_DE", nullable = false, length = 100)
	public String getSEmailDe() {
		return this.SEmailDe;
	}

	public void setSEmailDe(String SEmailDe) {
		this.SEmailDe = SEmailDe;
	}

	@Column(name = "X_FORMATO_EMAIL")
	public Blob getXFormatoEmail() {
		return this.XFormatoEmail;
	}

	public void setXFormatoEmail(Blob XFormatoEmail) {
		this.XFormatoEmail = XFormatoEmail;
	}

	@Column(name = "D_ASUNTO", nullable = false, length = 100)
	public String getDAsunto() {
		return this.DAsunto;
	}

	public void setDAsunto(String DAsunto) {
		this.DAsunto = DAsunto;
	}

	@Column(name = "S_SQL", nullable = false)
	public String getSSql() {
		return this.SSql;
	}

	public void setSSql(String SSql) {
		this.SSql = SSql;
	}

	@Column(name = "S_SQL_1")
	public String getSSql1() {
		return this.SSql1;
	}

	public void setSSql1(String SSql1) {
		this.SSql1 = SSql1;
	}

	@Column(name = "S_SQL_2")
	public String getSSql2() {
		return this.SSql2;
	}

	public void setSSql2(String SSql2) {
		this.SSql2 = SSql2;
	}

}
