package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbFormulariosSecciones generated by hbm2java
 */
@Entity
@Table(name = "TB_FORMULARIOS_SECCIONES", schema = "CATALOGOS")
public class TbFormulariosSecciones implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer cseccion;
    private TbFormularios tbFormularios;
    private String dseccion;
    private Integer bmultiRegistro;
    private Integer norden;
    private String stabla;
    private Integer bestado;
    private String cusuario;
    private Date fingreso;
    private String snotas;
    private String sdocumental;
    private String svalidacion;
    private String sfiscalizacion;
    private String ssql;
    private String stransforma;
    private Integer cdisenoWeb;
    private String ddisenoWeb;
    private Set<TbFormulariosCampos> tbFormulariosCamposes = new HashSet<TbFormulariosCampos>(
            0);

    public TbFormulariosSecciones() {
    }

    public TbFormulariosSecciones(Integer cseccion, String dseccion,
            Integer bmultiRegistro, Integer norden, Integer bestado,
            String cusuario, Date fingreso) {
        this.cseccion = cseccion;
        this.dseccion = dseccion;
        this.bmultiRegistro = bmultiRegistro;
        this.norden = norden;
        this.bestado = bestado;
        this.cusuario = cusuario;
        this.fingreso = fingreso;
    }

    public TbFormulariosSecciones(Integer cseccion,
            TbFormularios tbFormularios, String dseccion,
            Integer bmultiRegistro, Integer norden, String stabla,
            Integer bestado, String cusuario, Date fingreso, String snotas,
            String sdocumental, String svalidacion, String sfiscalizacion,
            String ssql, String stransforma,
            Set<TbFormulariosCampos> tbFormulariosCamposes) {
        this.cseccion = cseccion;
        this.tbFormularios = tbFormularios;
        this.dseccion = dseccion;
        this.bmultiRegistro = bmultiRegistro;
        this.norden = norden;
        this.stabla = stabla;
        this.bestado = bestado;
        this.cusuario = cusuario;
        this.fingreso = fingreso;
        this.snotas = snotas;
        this.sdocumental = sdocumental;
        this.svalidacion = svalidacion;
        this.sfiscalizacion = sfiscalizacion;
        this.ssql = ssql;
        this.stransforma = stransforma;
        this.tbFormulariosCamposes = tbFormulariosCamposes;
    }

    @Id
    @Column(name = "C_SECCION", unique = true, nullable = false, precision = 4, scale = 0)
    public Integer getCseccion() {
        return this.cseccion;
    }

    public void setCseccion(Integer cseccion) {
        this.cseccion = cseccion;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "C_FORMULARIO")
    public TbFormularios getTbFormularios() {
        return this.tbFormularios;
    }

    public void setTbFormularios(TbFormularios tbFormularios) {
        this.tbFormularios = tbFormularios;
    }

    @Column(name = "D_SECCION", nullable = false, length = 80)
    public String getDseccion() {
        return this.dseccion;
    }

    public void setDseccion(String dseccion) {
        this.dseccion = dseccion;
    }

    @Column(name = "B_MULTI_REGISTRO", nullable = false, precision = 1, scale = 0)
    public Integer getBmultiRegistro() {
        return this.bmultiRegistro;
    }

    public void setBmultiRegistro(Integer bmultiRegistro) {
        this.bmultiRegistro = bmultiRegistro;
    }

    @Column(name = "N_ORDEN", nullable = false, precision = 2, scale = 0)
    public Integer getNorden() {
        return this.norden;
    }

    public void setNorden(Integer norden) {
        this.norden = norden;
    }

    @Column(name = "S_TABLA")
    public String getStabla() {
        return this.stabla;
    }

    public void setStabla(String stabla) {
        this.stabla = stabla;
    }

    @Column(name = "B_ESTADO", nullable = false, precision = 1, scale = 0)
    public Integer getBestado() {
        return this.bestado;
    }

    public void setBestado(Integer bestado) {
        this.bestado = bestado;
    }

    @Column(name = "C_USUARIO", nullable = false, length = 40)
    public String getCusuario() {
        return this.cusuario;
    }

    public void setCusuario(String cusuario) {
        this.cusuario = cusuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "F_INGRESO", nullable = false, length = 7)
    public Date getFingreso() {
        return this.fingreso;
    }

    public void setFingreso(Date fingreso) {
        this.fingreso = fingreso;
    }

    @Column(name = "S_NOTAS")
    public String getSnotas() {
        return this.snotas;
    }

    public void setSnotas(String snotas) {
        this.snotas = snotas;
    }

    @Column(name = "S_DOCUMENTAL")
    public String getSdocumental() {
        return this.sdocumental;
    }

    public void setSdocumental(String sdocumental) {
        this.sdocumental = sdocumental;
    }

    @Column(name = "S_VALIDACION")
    public String getSvalidacion() {
        return this.svalidacion;
    }

    public void setSvalidacion(String svalidacion) {
        this.svalidacion = svalidacion;
    }

    @Column(name = "S_FISCALIZACION")
    public String getSfiscalizacion() {
        return this.sfiscalizacion;
    }

    public void setSfiscalizacion(String sfiscalizacion) {
        this.sfiscalizacion = sfiscalizacion;
    }

    @Column(name = "S_SQL", length = 4000)
    public String getSsql() {
        return this.ssql;
    }

    public void setSsql(String ssql) {
        this.ssql = ssql;
    }

    @Column(name = "S_TRANSFORMA", length = 4000)
    public String getStransforma() {
        return this.stransforma;
    }

    @Column(name = "C_DISENO_WEB", precision = 5, scale = 0)
    public Integer getCdisenoWeb() {
        return cdisenoWeb;
    }

    public void setCdisenoWeb(Integer cdisenoWeb) {
        this.cdisenoWeb = cdisenoWeb;
    }

    @Column(name = "D_DISENO_WEB")
    public String getDdisenoWeb() {
        return this.ddisenoWeb;
    }

    public void setDdisenoWeb(String ddisenoWeb) {
        this.ddisenoWeb = ddisenoWeb;
    }

    public void setStransforma(String stransforma) {
        this.stransforma = stransforma;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tbFormulariosSecciones")
    public Set<TbFormulariosCampos> getTbFormulariosCamposes() {
        return this.tbFormulariosCamposes;
    }

    public void setTbFormulariosCamposes(
            Set<TbFormulariosCampos> tbFormulariosCamposes) {
        this.tbFormulariosCamposes = tbFormulariosCamposes;
    }
}
