package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbFormulariosCamposId generated by hbm2java
 */
@Embeddable
public class TbFormulariosCamposId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer cformulario;
	private Integer cversion;
	private Integer ccampo;

	public TbFormulariosCamposId() {
	}

	public TbFormulariosCamposId(Integer cformulario, Integer cversion,
			Integer ccampo) {
		this.cformulario = cformulario;
		this.cversion = cversion;
		this.ccampo = ccampo;
	}

	@Column(name = "C_FORMULARIO", nullable = false, precision = 4, scale = 0)
	public Integer getCformulario() {
		return this.cformulario;
	}

	public void setCformulario(Integer cformulario) {
		this.cformulario = cformulario;
	}

	@Column(name = "C_VERSION", nullable = false, precision = 4, scale = 0)
	public Integer getCversion() {
		return this.cversion;
	}

	public void setCversion(Integer cversion) {
		this.cversion = cversion;
	}

	@Column(name = "C_CAMPO", nullable = false, precision = 4, scale = 0)
	public Integer getCcampo() {
		return this.ccampo;
	}

	public void setCcampo(Integer ccampo) {
		this.ccampo = ccampo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbFormulariosCamposId))
			return false;
		TbFormulariosCamposId castOther = (TbFormulariosCamposId) other;

		return ((this.getCformulario() == castOther.getCformulario()) || (this
				.getCformulario() != null
				&& castOther.getCformulario() != null && this.getCformulario()
				.equals(castOther.getCformulario())))
				&& ((this.getCversion() == castOther.getCversion()) || (this
						.getCversion() != null
						&& castOther.getCversion() != null && this
						.getCversion().equals(castOther.getCversion())))
				&& ((this.getCcampo() == castOther.getCcampo()) || (this
						.getCcampo() != null
						&& castOther.getCcampo() != null && this.getCcampo()
						.equals(castOther.getCcampo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCformulario() == null ? 0 : this.getCformulario()
						.hashCode());
		result = 37 * result
				+ (getCversion() == null ? 0 : this.getCversion().hashCode());
		result = 37 * result
				+ (getCcampo() == null ? 0 : this.getCcampo().hashCode());
		return result;
	}

}
