package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * TbImportancia generated by hbm2java
 */
@Entity
@Table(name = "TB_IMPORTANCIA", schema = "CATALOGOS")
public class TbImportancia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cimportancia;
	private String cusuario;
	private String dimportancia;
	private Date fhingreso;
	private Integer bstatus;
	private Integer bdefault;
	
	private Set<RcRuc> rcRucs = new HashSet<RcRuc>(0);

	public TbImportancia() {
	}

	public TbImportancia(String cimportancia, String cusuario,
			String dimportancia, Date fhingreso, Integer bstatus,
			Integer bdefault) {
		this.cimportancia = cimportancia;
		this.cusuario = cusuario;
		this.dimportancia = dimportancia;
		this.fhingreso = fhingreso;
		this.bstatus = bstatus;
		this.bdefault = bdefault;
	}

	

	@Id
	@Column(name = "C_IMPORTANCIA", unique = true, nullable = false, length = 1)
	public String getCimportancia() {
		return this.cimportancia;
	}

	public void setCimportancia(String cimportancia) {
		this.cimportancia = cimportancia;
	}

	@Column(name = "C_USUARIO", nullable = false, length = 30)
	public String getCusuario() {
		return this.cusuario;
	}

	public void setCusuario(String cusuario) {
		this.cusuario = cusuario;
	}

	@Column(name = "D_IMPORTANCIA", nullable = false, length = 20)
	public String getDimportancia() {
		return this.dimportancia;
	}

	public void setDimportancia(String dimportancia) {
		this.dimportancia = dimportancia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FH_INGRESO", nullable = false, length = 7)
	public Date getFhingreso() {
		return this.fhingreso;
	}

	public void setFhingreso(Date fhingreso) {
		this.fhingreso = fhingreso;
	}

	@Column(name = "B_STATUS", nullable = false, precision = 1, scale = 0)
	public Integer getBstatus() {
		return this.bstatus;
	}

	public void setBstatus(Integer bstatus) {
		this.bstatus = bstatus;
	}

	@Column(name = "B_DEFAULT", nullable = false, precision = 1, scale = 0)
	public Integer getBdefault() {
		return this.bdefault;
	}

	public void setBdefault(Integer bdefault) {
		this.bdefault = bdefault;
	}

	

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tbImportancia")	
	public Set<RcRuc> getRcRucs() {
		return this.rcRucs;
	}

	public void setRcRucs(Set<RcRuc> rcRucs) {
		this.rcRucs = rcRucs;
	}

}
