package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TbListasValor generated by hbm2java
 */
@Entity
@Table(name = "TB_LISTAS_VALOR", schema = "")
public class TbListasValor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private TbListasValorId id;
	private String dlista;
	private Integer bstatus;
	private String cusuario;
	private Date fingreso;
	private List<String> excludedValues = new ArrayList<String>(0);
	private List<String> includedValues = new ArrayList<String>(0);
	private Integer systemValue;
	private Set<TbListasValorDet> tbListasValorDets = new HashSet<TbListasValorDet>(
			0);

	public TbListasValor() {
	}

	public TbListasValor(TbListasValorId id) {
		this.id = id;
	}

	public TbListasValor(TbListasValorId id, String dlista, Integer bstatus,
			String cusuario, Date fingreso,
			Set<TbListasValorDet> tbListasValorDets) {
		this.id = id;
		this.dlista = dlista;
		this.bstatus = bstatus;
		this.cusuario = cusuario;
		this.fingreso = fingreso;
		this.tbListasValorDets = tbListasValorDets;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "clista", column = @Column(name = "C_LISTA", nullable = false, length = 50)),
			@AttributeOverride(name = "cmodulo", column = @Column(name = "C_MODULO", nullable = false, length = 50)) })
	public TbListasValorId getId() {
		return this.id;
	}

	public void setId(TbListasValorId id) {
		this.id = id;
	}

	@Column(name = "D_LISTA")
	public String getDlista() {
		return this.dlista;
	}

	public void setDlista(String dlista) {
		this.dlista = dlista;
	}

	@Column(name = "B_STATUS", precision = 1, scale = 0)
	public Integer getBstatus() {
		return this.bstatus;
	}

	public void setBstatus(Integer bstatus) {
		this.bstatus = bstatus;
	}

	@Column(name = "C_USUARIO", length = 30)
	public String getCusuario() {
		return this.cusuario;
	}

	public void setCusuario(String cusuario) {
		this.cusuario = cusuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_INGRESO", length = 7)
	public Date getFingreso() {
		return this.fingreso;
	}

	public void setFingreso(Date fingreso) {
		this.fingreso = fingreso;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tbListasValor")
	public Set<TbListasValorDet> getTbListasValorDets() {
		return this.tbListasValorDets;
	}

	public void setTbListasValorDets(Set<TbListasValorDet> tbListasValorDets) {
		this.tbListasValorDets = tbListasValorDets;
	}
	@Column(name = "SYSTEM_VALUE", precision = 1, scale = 0)
	public Integer getSystemValue() {
		return this.systemValue;
	}

	public void setSystemValue(Integer systemValue) {
		this.systemValue = systemValue;
	}
	@Transient
	public List<String> getExcludedValues() {
		return excludedValues;
	}

	public void setExcludedValues(List<String> excludedValues) {
		this.excludedValues = excludedValues;
	}
	@Transient
	public List<String> getIncludedValues() {
		return includedValues;
	}

	public void setIncludedValues(List<String> includedValues) {
		this.includedValues = includedValues;
	}
	
 

}
