package sv.global.colas.entities;
// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbListasValorId generated by hbm2java
 */
@Embeddable
public class TbListasValorId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String clista;
	private String cmodulo;
        
	public TbListasValorId() {
	}

	public TbListasValorId(String clista, String cmodulo) {
		this.clista = clista;
		this.cmodulo = cmodulo;
	}

	@Column(name = "C_LISTA", nullable = false, length = 50)
	public String getClista() {
		return this.clista;
	}

	public void setClista(String clista) {
		this.clista = clista;
	}

	@Column(name = "C_MODULO", nullable = false, length = 50)
	public String getCmodulo() {
		return this.cmodulo;
	}

	public void setCmodulo(String cmodulo) {
		this.cmodulo = cmodulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbListasValorId))
			return false;
		TbListasValorId castOther = (TbListasValorId) other;

		return ((this.getClista() == castOther.getClista()) || (this
				.getClista() != null
				&& castOther.getClista() != null && this.getClista().equals(
				castOther.getClista())))
				&& ((this.getCmodulo() == castOther.getCmodulo()) || (this
						.getCmodulo() != null
						&& castOther.getCmodulo() != null && this.getCmodulo()
						.equals(castOther.getCmodulo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getClista() == null ? 0 : this.getClista().hashCode());
		result = 37 * result
				+ (getCmodulo() == null ? 0 : this.getCmodulo().hashCode());
		return result;
	}

}
