package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbMunicipioId generated by hbm2java
 */
@Embeddable
public class TbMunicipioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cdepartamento;
	private String cmunicipio;

	public TbMunicipioId() {
	}

	public TbMunicipioId(String cdepartamento, String cmunicipio) {
		this.cdepartamento = cdepartamento;
		this.cmunicipio = cmunicipio;
	}

	@Column(name = "C_DEPARTAMENTO", nullable = false, length = 2)
	public String getCdepartamento() {
		return this.cdepartamento;
	}

	public void setCdepartamento(String cdepartamento) {
		this.cdepartamento = cdepartamento;
	}

	@Column(name = "C_MUNICIPIO", nullable = false, length = 2)
	public String getCmunicipio() {
		return this.cmunicipio;
	}

	public void setCmunicipio(String cmunicipio) {
		this.cmunicipio = cmunicipio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbMunicipioId))
			return false;
		TbMunicipioId castOther = (TbMunicipioId) other;

		return ((this.getCdepartamento() == castOther.getCdepartamento()) || (this
				.getCdepartamento() != null
				&& castOther.getCdepartamento() != null && this
				.getCdepartamento().equals(castOther.getCdepartamento())))
				&& ((this.getCmunicipio() == castOther.getCmunicipio()) || (this
						.getCmunicipio() != null
						&& castOther.getCmunicipio() != null && this
						.getCmunicipio().equals(castOther.getCmunicipio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCdepartamento() == null ? 0 : this.getCdepartamento()
						.hashCode());
		result = 37
				* result
				+ (getCmunicipio() == null ? 0 : this.getCmunicipio()
						.hashCode());
		return result;
	}

    @Override
    public String toString() {
        return "TbMunicipioId{" + "cdepartamento=" + cdepartamento + ", cmunicipio=" + cmunicipio + '}';
    }
        
        

}
