package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbTipoFormulario generated by hbm2java
 */
@Entity
@Table(name = "TB_TIPO_FORMULARIO", schema = "CATALOGOS")
public class TbTipoFormulario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String ctipoFormulario;
	private String dtipoFormulario;
	private String stipoFormulario;
	private String snotas;
	private String cusuario;
	private Date fingreso;
	private Set<TbFormularios> tbFormularioses = new HashSet<TbFormularios>(0);

	public TbTipoFormulario() {
	}

	public TbTipoFormulario(String ctipoFormulario, String dtipoFormulario,
			String stipoFormulario, String cusuario, Date fingreso) {
		this.ctipoFormulario = ctipoFormulario;
		this.dtipoFormulario = dtipoFormulario;
		this.stipoFormulario = stipoFormulario;
		this.cusuario = cusuario;
		this.fingreso = fingreso;
	}

	public TbTipoFormulario(String ctipoFormulario, String dtipoFormulario,
			String stipoFormulario, String snotas, String cusuario,
			Date fingreso, Set<TbFormularios> tbFormularioses) {
		this.ctipoFormulario = ctipoFormulario;
		this.dtipoFormulario = dtipoFormulario;
		this.stipoFormulario = stipoFormulario;
		this.snotas = snotas;
		this.cusuario = cusuario;
		this.fingreso = fingreso;
		this.tbFormularioses = tbFormularioses;
	}

	@Id
	@Column(name = "C_TIPO_FORMULARIO", unique = true, nullable = false, length = 3)
	public String getCtipoFormulario() {
		return this.ctipoFormulario;
	}

	public void setCtipoFormulario(String ctipoFormulario) {
		this.ctipoFormulario = ctipoFormulario;
	}

	@Column(name = "D_TIPO_FORMULARIO", nullable = false)
	public String getDtipoFormulario() {
		return this.dtipoFormulario;
	}

	public void setDtipoFormulario(String dtipoFormulario) {
		this.dtipoFormulario = dtipoFormulario;
	}

	@Column(name = "S_TIPO_FORMULARIO", nullable = false, length = 80)
	public String getStipoFormulario() {
		return this.stipoFormulario;
	}

	public void setStipoFormulario(String stipoFormulario) {
		this.stipoFormulario = stipoFormulario;
	}

	@Column(name = "S_NOTAS")
	public String getSnotas() {
		return this.snotas;
	}

	public void setSnotas(String snotas) {
		this.snotas = snotas;
	}

	@Column(name = "C_USUARIO", nullable = false, length = 40)
	public String getCusuario() {
		return this.cusuario;
	}

	public void setCusuario(String cusuario) {
		this.cusuario = cusuario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "F_INGRESO", nullable = false, length = 7)
	public Date getFingreso() {
		return this.fingreso;
	}

	public void setFingreso(Date fingreso) {
		this.fingreso = fingreso;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tbTipoFormulario")
	public Set<TbFormularios> getTbFormularioses() {
		return this.tbFormularioses;
	}

	public void setTbFormularioses(Set<TbFormularios> tbFormularioses) {
		this.tbFormularioses = tbFormularioses;
	}

}
