package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbTipoContribId generated by hbm2java
 */
@Embeddable
public class TbTipoContribId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cclase;
	private String ctipo;

	public TbTipoContribId() {
	}

	public TbTipoContribId(String cclase, String ctipo) {
		this.cclase = cclase;
		this.ctipo = ctipo;
	}

	@Column(name = "C_CLASE", nullable = false, length = 1)
	public String getCclase() {
		return this.cclase;
	}

	public void setCclase(String cclase) {
		this.cclase = cclase;
	}

	@Column(name = "C_TIPO", nullable = false, length = 4)
	public String getCtipo() {
		return this.ctipo;
	}

	public void setCtipo(String ctipo) {
		this.ctipo = ctipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbTipoContribId))
			return false;
		TbTipoContribId castOther = (TbTipoContribId) other;

		return ((this.getCclase() == castOther.getCclase()) || (this
				.getCclase() != null
				&& castOther.getCclase() != null && this.getCclase().equals(
				castOther.getCclase())))
				&& ((this.getCtipo() == castOther.getCtipo()) || (this
						.getCtipo() != null
						&& castOther.getCtipo() != null && this.getCtipo()
						.equals(castOther.getCtipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCclase() == null ? 0 : this.getCclase().hashCode());
		result = 37 * result
				+ (getCtipo() == null ? 0 : this.getCtipo().hashCode());
		return result;
	}
        
        public String toString(){
            return this.cclase+"|"+this.ctipo;
        }

}
