package sv.global.colas.entities;

// Generated Dec 12, 2007 3:08:52 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbTramiteId generated by hbm2java
 */
@Embeddable
public class TbTramiteId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cgestion;
	private String ctramite;

	public TbTramiteId() {
	}

	public TbTramiteId(String cgestion, String ctramite) {
		this.cgestion = cgestion;
		this.ctramite = ctramite;
	}

	@Column(name = "C_GESTION", nullable = false, length = 1)
	public String getCgestion() {
		return this.cgestion;
	}

	public void setCgestion(String cgestion) {
		this.cgestion = cgestion;
	}

	@Column(name = "C_TRAMITE", nullable = false, length = 3)
	public String getCtramite() {
		return this.ctramite;
	}

	public void setCtramite(String ctramite) {
		this.ctramite = ctramite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbTramiteId))
			return false;
		TbTramiteId castOther = (TbTramiteId) other;

		return ((this.getCgestion() == castOther.getCgestion()) || (this
				.getCgestion() != null
				&& castOther.getCgestion() != null && this.getCgestion()
				.equals(castOther.getCgestion())))
				&& ((this.getCtramite() == castOther.getCtramite()) || (this
						.getCtramite() != null
						&& castOther.getCtramite() != null && this
						.getCtramite().equals(castOther.getCtramite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCgestion() == null ? 0 : this.getCgestion().hashCode());
		result = 37 * result
				+ (getCtramite() == null ? 0 : this.getCtramite().hashCode());
		return result;
	}

}
